### ISSUE TITLE
Criar um modelo de ML para classificação do nome do responsável pelo ato

### ISSUE THREAD

**Issue by dansousamelo** [UnB-KnEDLe/timeline-contratos#113]
## Contexto

Visto que conseguimos pegar o nome do responsável pelo ato, o próximo passo é criar um modelo de ML para pegar essa entidade de modo mais assertivo.

## Objetivo 

* [x] Criar modelo para classificar entidade do nome do responsável pelo ato
* [ ] Garantir uma assertividade satisfatória do modelo
* [x] Conversar com o professor Tiago para entender como as entidades estão sendo retiradas dos atos de extrato de contrato

**Comment by Thais-ra** [comment]
Criamos o modelo do spacy para identificar os responsáveis pelo ato e agora estamos testando para começar a fase de integração com o Skweak.

**Comment by niltoncs** [comment]
Prof Thiago disse que tem modelos para identificação de nomes que podem ajudar nesta frente. Vcs não acham que vale a pena pedir para os alunos dele mostrar os resultados e os modelos utilizados?
