### ISSUE TITLE
Rotular dados de atos

### ISSUE THREAD

**Issue by fabraz** [UnB-KnEDLe/timeline-contratos#128]
# Descrição
Rotular os atos dos DODFs, considerando a duas amostras dos 21 anos de dados disponibilizados.

A rotulação acontecerá por meio do labelbox e exigirá que cada pesquisador crie sua conta na ferramenta e faça a configuração do projeto, sendo que os rótulos devem seguir o padrão especificado a seguir:

# Lista de Atos

- DESCONHECIDO
- AVISO DE ABERTURA DE LICITAÇÃO
- AVISO DE ADJUDICAÇÃO E HOMOLOGAÇÃO
- AVISO DE HOMOLOGAÇÃO E CONVOCAÇÃO
- AVISO DE CONVOCAÇÃO
- AVISO DE DECLARAÇÃO DE VENCEDOR
- AVISO DE RESULTADO
- AVISO DE RESULTADO DE JULGAMENTO
- AVISO DE JULGAMENTO
- AVISO DE LICITAÇÃO
- AVISO DE JULGAMENTO DE HABILITAÇÃO
- AVISO DE RESULTADO DE RECURSO E JULGAMENTO
- AVISO DE SUSPENSÃO DE LICITAÇÃO
- AVISO DE ADIAMENTO DE LICITAÇÃO
- AVISO DE ALTERAÇÃO
- **AVISO DE REVOGAÇÃO/ANULAÇÃO DE LICITAÇÃO**
- **EXTRATO DE CONTRATO OU CONVÊNIO**
- AVISO DE REABERTURA
- AVISO DE NOVA DATA DE ABERTURA
- **EXTRATO DE ADITAMENTO CONTRATUAL**

# Critérios de Aceitação
- [ ] Dados rotulados exportados para o formato  
- [ ] Notebook para aferição de reconhecimento de atos

**Comment by dansousamelo** [comment]
Achei outro tipo de ato que não estamos considerando:
AVISO DE RATIFICAÇÃO
Vou colocar como desconhecido
