### ISSUE TITLE
Preparar dataset para anotação de atos

### ISSUE THREAD

**Issue by fabraz** [UnB-KnEDLe/timeline-contratos#129]
# Descrição
Preparar conjuntos de atos rotulados para serem usados como insumo de rotulação de entidades.

# Critérios de Aceitação

- [x] Código para gerar os atos rotulados no labelbox
- [x] Salvar os atos anotados no github do projeto

**Comment by IanFPFerreira** [comment]
Usar o código para gerar os arquivos que irá conter todos os atos rotulados, sendo que cada ato estará em um arquivo que seguirá o padrão de nome "n°_titulo_do_ato_dodfs_de onde_foi_tirado_o_ato.txt". Com isso, basta colocar todos os arquivos em um novo projeto do Labelbox e utilizar as entidades que estão na issue #130. Preferimos usar um arquivo .txt para cada ato ao invés de um único arquivo com todos os atos, pois fica mais fácil para referenciar as entidades com o texto aonde elas foram rotuladas
