### ISSUE TITLE
Rotular entidades de atos

### ISSUE THREAD

**Issue by fabraz** [UnB-KnEDLe/timeline-contratos#130]
## Descrição
Possuindo em mãos os atos rotulados através do labelbox, utilizaremos esse mesmo site para rotular as entidades de cada ato encontrado.
O documento fornecido pelo cliente será usado como base para rotular essas entidades.

### Aviso de Licitação
- Órgão/ entidade licitante
- Número da licitação
- Objeto de licitação
- Modalidade de licitação. Exemplos: 
    - Concorrência
    - Tomada de Preços
    - Pregão Eletrônico
    - Pregão Presencial
    - Credenciamento
    - RDC, etc.
- Processo do GDF (número)
- Valor estimado da contratação
- Data de abertura da licitação (recebimento de propostas)
- Sistema de compras utilizado. Exemplos: 
    - ComprasNet
    - Licitaçãoes-e (Banco do Brasil)
    - ComprasDF
    - e-ComprasDF, etc
- Código da licitação no sistema de compras utilizado (UASG, etc)
- Tipo de objeto. Exemplos: 
    - Alienação de bens
    - Aquisições
    - Prestação de serviços
    - Concessão
    - Permissão
    - Locação
    - Obras e serviços de engenharia, etc.

### Aviso de Suspensão de licitação
- Órgão/ entidade licitante
- Número da licitação
- Modalidade de licitação. Exemplos: 
    - Concorrência
    - Tomada de Preços
    - Pregão Eletrônico
    - Pregão Presencial
    - Credenciamento
    - RDC, etc.
- Prazo de suspensão
- Decisão do TCDF que determinou a suspensão, quando mencionada.

### Aviso de Revogação/Anulação de licitação
- Órgão/ entidade licitante
- Número da licitação
- Modalidade de licitação. Exemplos: 
    - Concorrência
    - Tomada de Preços
    - Pregão Eletrônico
    - Pregão Presencial
    - Credenciamento
    - RDC, etc.
- Identificação da ocorrência de revogação ou anulação

### Extrato de contrato ou convênio
* Número do ajuste
* Órgão contratante (nome)
* Entidade contratada (nome e CNPJ)
* Entidades convenentes (apenas no caso de convênio)
* Processo do GDF (número)
* Objeto de ajuste
* Data de assinatura do ajuste
* Vigência do ajuste
* Valor do ajuste
* Dotação orçamentária, incluindo: 
    * Código da unidade orçamentária (U. O.)
    * Programa de trabalho
    * Natureza de despesa
    * Nota de empenho
* Quando contrato decorrente de licitação
    * Órgão licitante (nome)
    * Número da licitação que gerou o contrato
* Quando contrato decorrente da adesão a ARP
    * Órgão gerenciador da Ata (OG): nome
    * UF do OG
    * Nº do edital do OG
    * Ano do edital do OG
* Quando contrato decorrente de dispensa ou inexigibilidade
    * Fundamento legal da dispensa ou inexigibilidade
    * Caso o fundamento legal não seja informado, identificar se foi dispensa de licitação ou inexigibilidade. 
 
 ### Extrato de aditamento contratual
* Órgão contratante (nome)
* Número do contrato
* Número do termo aditivo (Ex: "Oitavo Termo Aditivo")
* Objeto do aditamento contratual
Obs: as vezes, o objeto é múltiplo. Por exemplo:
    * Prorrogação de vigência contratual; e
    * Alteração do valor contratual

**Comment by ciriatico** [comment]
Para registro no Labelbox, usaremos essa lista com 37 entidades:

- Órgão/entidade licitante
- Número da licitação
- Objeto da licitação
- Modalidade de licitação
- Processo do GDF
- Valor estimado da contratação
- Data de abertura da licitação
- Sistema de compras utilizado
- Código da licitação no sistema de compras utilizado
- Tipo de objeto
- Prazo da suspensão
- Decisão do TCDF que determinou a suspensão
- Modalide de licitação
- Revogação
- Anulação
- Número do ajuste
- Órgão contratante
- Entidade contratada
- Entidades convenentes
- Objeto do ajuste
- Data de assinatura do ajuste
- Vigência do ajuste
- Valor do ajuste
- Código da unidade orçamentária
- Programa de trabalho
- Natureza da despesa
- Nota de empenho
- Número da licitação que gerou o contrato
- Órgão gerenciador da ata
- UF do OG
- Número do edital do OG
- Ano do edital do OG
- Fundamento legal da dispensa ou inexigibilidade
- Dispensa de licitação
- Dispensa de inexigibilidade
- Número do contrato
- Número do termo aditivo
