### ISSUE TITLE
Modelar banco de dados em Grafo

### ISSUE THREAD

**Issue by dansousamelo** [UnB-KnEDLe/timeline-contratos#145]
# Descrição

Estudar a respeito de banco de dados baseado em grafos e modelar uma solução

# Critérios de Aceitação

- [x] Estudar sobre banco de dados baseados em grafo
- [x] Modelagem da Versão 1 do modelo de  banco de dados 
- [x] Modelagem da Versão 2 do modelo de  banco de dados
- [ ] Modelagem da Versão 3 do modelo de  banco de dados

**Comment by Maiconrq** [comment]
Hoje se dá inicio a modelagem da versão 2 do modelo de banco de dados.
