### ISSUE TITLE
Atualizar os REGEX e colocar os dados no repositório

### ISSUE THREAD

**Issue by thiagodepaulo** [UnB-KnEDLe/timeline-contratos#150]
# Descrição

Visto que os REGEX não estão muito assertivos devemos atualizá-los, colocando os dados em nosso repositório.

# Critérios de Aceitação

- [x] Atualizar REGEX e testar assertividade
- [ ] Colocar atos no repositório (supenso)
- [ ] Realizar modelagem v1 (suspenso)

--------------------
- [x] Corrigir problema no Regex referente à quebra de página

**Comment by aliceborges42** [comment]
pessoal, posso fechar essa issue?
