### ISSUE TITLE
Criar modelo usando algoritmo CRF para NER dos atos de licitação.

### ISSUE THREAD

**Issue by andlq** [UnB-KnEDLe/timeline-contratos#162]
# Descrição

Os scripts para a criação desse modelo estão no repositório  https://github.com/UnB-KnEDLe/experiments na pasta members/thais/estudo_crf

# Critérios de Aceitação

- [X] Resolver bug relacionado a diferença entre os dados de treinamento (X) e anotações (Y)
- [X] Criar modelo usando CRF utilizando os dados rotulados
- [X] Avaliar o modelo (f1-score, recall)
- [x] Melhorar os resultado do crf (adicionar features, ajustar hiperparametros...)
- [x] Avaliar modelo usando 10 fold cross-validation
- [x]  Contar os tipos de ato que estao sendo usados
- [x] Continuar o treinamento com aviso de licitação
- [x] Adicionar features levando em consideração palavras anteriores e posteriores
- [x] Apagar Labels nao usadas

**Comment by aliceborges42** [comment]
Essa issue deve estar no to do mesmo ou no in progress? tive a impressão que ja foi iniciada

**Comment by aliceborges42** [comment]
Posso mover essa issue para closed?
