### ISSUE TITLE
estudar snorkel

### ISSUE THREAD

**Issue by tucazorron** [UnB-KnEDLe/timeline-contratos#18]

**Comment by Luceliafn** [comment]
Realizado a instalação da biblioteca conforme tutorial https://www.snorkel.org/get-started/
executado também o tutorial spam obtido https://github.com/snorkel-team/snorkel-tutorials

**Comment by Luceliafn** [comment]
Observado que a versão continuada da ferramenta não é livre.. a versão que está sendo trabalhada é a versão https://snorkel.ai/ a qual é comercializada.
