### ISSUE TITLE
Migrar para o banco Neo4j

### ISSUE THREAD

**Issue by dansousamelo** [UnB-KnEDLe/timeline-contratos#35]
* [ ]  Entender conceitos do Neo4j
* [ ] Implementar banco de dados em Neo4j

**Comment by guilherme-mendes** [comment]
Segue o link do notebook demostrado na reunião passada do neo4j
https://github.com/UnB-KnEDLe/experiments/tree/master/members/guilherme/neo4j

**Comment by aliceborges42** [comment]
@dansousamelo como está o andamento dessa issue?
