### ISSUE TITLE
Definir/escrever o problema de pesquisa 

### ISSUE THREAD

**Issue by thiagodepaulo** [UnB-KnEDLe/timeline-contratos#4]
Detecção de Fraudes em Contratos

**Comment by Luceliafn** [comment]
Após conversa com a especialista Karla, reunião com o colega Linderbeg e Professor Thiago, optou-se por mudar o enfoque da pesquisa para Supervisão Fraca. Tendo em vista a falta de especialista para auxiliar na rotulação dos casos de Fraudes.
