### ISSUE TITLE
Revisar REGEX das ENTIDADES com novos blocos

### ISSUE THREAD

**Issue by fabraz** [UnB-KnEDLe/timeline-contratos#84]
* [x] Número do Processo
* [x] Data
* [x] Empresas Vencedoras
* [x] Itens Vencedores
* [x] Itens Fracassados
* [x] CNPJ
* [x] Nome do Responsável pelo Ato

**Comment by IanFPFerreira** [comment]
Empresas + CNPJ + Itens vencedores:

https://regex101.com/r/qkTJZI/1

**Comment by IanFPFerreira** [comment]
CNPJ:

https://regex101.com/r/saUWQh/1
