### ISSUE TITLE
Extrair os atos de Contrato com REGEX

### ISSUE THREAD

**Issue by thiagodepaulo** [UnB-KnEDLe/timeline-contratos#99]

**Comment by ciriatico** [comment]
Primeira versão de código de extração feita e colocada no git de experimentos. Extração feita em cima dos documentos disponibilizados pelo professor Fabrício, indo de 2000 a 2021, resultando no dataframe dodf_texts_regex.parquet, com os extratos extraídos por REGEX.
https://github.com/UnB-KnEDLe/experiments/tree/master/members/ciriatico/extrato_regex_extractor
